version: '3'
services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    tty: false
    stdin_open: false

  go:
    container_name: api
    build:
      context: ./go-app
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    env_file:
      - ${ENV_FILE:-variables.env}
    networks:
      - golang_networks
    tty: false
    stdin_open: false

networks:
  golang_networks:
    external: true
