FROM golang:1.22.1 AS builder
WORKDIR /app/go-app

# 依存関係をキャッシュするためにモジュールファイルを先にコピー
COPY go.mod go.sum ./
RUN go mod download

# ソースコードをコピーしてビルド
COPY ./ ./

# デバッグ用にディレクトリの内容を表示
RUN echo "Checking the contents of go-app directory:" && ls -R ./go-app

RUN go build -o ./cmd/main ./cmd/main.go

# 実行用の軽量イメージ
FROM debian:bookworm-slim
WORKDIR /app/go-app

# ビルドしたバイナリのみをコピー
COPY --from=builder /app/go-app/cmd/main .

# 実行
ENTRYPOINT [ "./main" ]
